version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
pull_requests:
  do_not_increment_build_number: true
install:
  - ps: |
      $env:DOTNET_INSTALL_DIR = "..\.dotnetsdk"
      mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
      Invoke-WebRequest -Uri "https://raw.githubusercontent.com/dotnet/cli/release/2.1.2xx/scripts/obtain/dotnet-install.ps1" -OutFile "$($env:DOTNET_INSTALL_DIR)\dotnet-install.ps1"
      & "$($env:DOTNET_INSTALL_DIR)\dotnet-install.ps1" -Version 2.1.200 -InstallDir $env:DOTNET_INSTALL_DIR
      $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
      choco install docker-compose
      & "$($env:DOTNET_INSTALL_DIR)\dotnet" --info
before_build:
  - ps: |
      & "$($env:DOTNET_INSTALL_DIR)\dotnet" restore CSDiscordService\CSDiscordService.csproj --configfile ..\.nuget\nuget.config
      & "$($env:DOTNET_INSTALL_DIR)\dotnet" restore CSDiscordService.Tests\CSDiscordService.Tests.csproj --configfile ..\.nuget\nuget.config
  - 7z a deploy-script.zip before-deploy.ps1
build_script:
  - ps: |
      cd CSDiscordService
      & "$($env:DOTNET_INSTALL_DIR)\dotnet" publish --configuration Release --output obj/Docker/publish
      cd ..
  - docker-compose build
test_script:
  - docker run -d -e "tokens=test" -p 80:80/tcp --name CSDiscord --net nat csdiscordservice
  - ps: |
      $json = (& "docker" "inspect" "CSDiscord" | ConvertFrom-Json)
      $address= $json.NetworkSettings.Networks.nat.ipaddress
      iwr -uri "http://$address/Eval" -method POST -contentType "text/plain" -body "1+1" -UseBasicParsing -Headers @{"Authorization"="Token test"}
  - docker stop CSDiscord
  - docker rm CSDiscord
after_build:
  - ps: |
      if(-not [System.String]::IsNullOrWhitespace($env:APPVEYOR_PULL_REQUEST_NUMBER)) {	return; }
      $branchtag = $env:APPVEYOR_REPO_BRANCH
      $committag = $env:APPVEYOR_REPO_COMMIT
      if([System.String]::IsNullOrWhitespace($branchtag)) { $branchtag = "untagged" }
      docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
      docker tag csdiscordservice cisien/csdiscord:$branchtag
      docker tag csdiscordservice cisien/csdiscord:$committag
      docker push cisien/csdiscord:$branchtag
      docker push cisien/csdiscord:$committag
artifacts:
  - path: deploy-script.zip
    name: deploy-script
deploy:
  - provider: Environment
    name: spartanhost
    on:
      branch: master
environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOCKER_USER:
    secure: ry9x9cQ9gzMNaPOd45RSHQ==
  DOCKER_PASS:
    secure: AXXeju7g+0ZE1ZMW2TKcXfW6+CMT70ZDh5iWYE5Bg80=
  TOKENS:
    secure: 20GDZBJStUXBheGueyX+iIXiRK6E/npU6vn2OA6s+NzIq96C+33xZblQbSwUt6BtYCr3duMGuiwaCayUR20SYVWCYo1I2IBZq+uUUtTZVfk=
  LOG_WEBHOOK_TOKEN:
    secure: /QjuIMGkGJIDgoyw+zeIsQQKjcbnrmydGAjcOhzYvFPHy2CFoev9vd2Bq8gv+oA/dUVv8mFShqPqvzFq+1PkwdUMIYVB21wcTRENTA4FjjQ=
