version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
pull_requests:
  do_not_increment_build_number: true
install:
  - ps: iwr -uri "https://download.microsoft.com/download/6/1/B/61B3E81F-5509-48D2-BB4F-5189E23CD29A/dotnet-sdk-2.0.0-preview2-006497-win-x64.exe" -out dotnet-sdk-2.0.0.exe
  - ps: .\dotnet-sdk-2.0.0.exe /install /passive
before_build:
  - ps: Push-Location
  - ps: cd ./CSDiscordService/
  - ps: dotnet --info
  - ps: Pop-Location
  - ps: dotnet restore --configfile .nuget/nuget.config
build_script:
  - ps: dotnet build CSDiscord.sln --configuration Release
  - ps: Push-Location
  - ps: cd ./CSDiscordService/
  - ps: dotnet publish --configuration Release
  - ps: copy ..\manifest.xml "bin\Any CPU\Release\netcoreapp2.0\manifest.xml"
  - ps: mkdir c:\projects\csdiscord\artifacts
  - ps: '&"c:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" ''-verb:sync'' ''-source:archiveDir="C:\projects\csdiscord\CSDiscordService\bin\Any CPU\Release\netcoreapp2.0"'' ''-dest:package="c:\projects\csdiscord\artifacts\CSDiscordService.zip"'' ''-declareParam:name="IIS Web Application Name",defaultValue="csdiscordservice",tags="IisApp"'' ''-declareParam:name="IIS Web Application Name",type="ProviderPath",scope="IisApp",match="^.*csdiscordservice$"'' ''-declareParam:name="IIS Web Application Name",type="ProviderPath",scope="setAcl",match="^.*csdiscordservice'''
  - ps: Pop-Location
test_script:
  - ps: Push-Location
  - ps: cd ./CSDiscordService.Tests/
  - ps: dotnet xunit
  - ps: Pop-Location
artifacts:
- path: artifacts/CSDiscordService.zip
  name: CSDiscordFunction
  type: WebDeployPackage
deploy:
- provider: WebDeploy
  server: https://csdiscordservice.scm.azurewebsites.net:443/msdeploy.axd?site=csdiscordservice
  website: csdiscordservice
  username: $csdiscordservice
  password:
    secure: 7ZZv5auxcejdquiVPI7WEu+gJ7DHESAN0yudFAYMpMd4enJChl20Fw5XVNyYW8HB+OGP4THbSqCN/qorYExNBw==
  artifact: CSDiscordFunction
  remove_files: true
  app_offline: true
after_deploy:
- ps: iwr -uri http://csdiscordservice.azurewebsites.net/Eval -UseBasicParsing -Body "1+1" -Method Post -ContentType text/plain -Headers @{"Authorize"=${$env:api_token}}
environment:
  api_token:
    secure: GroejrzfkoqNfBomrM4kTrBhT9PoueDewcScZe81dYrqU42xc4WRH2gbNib7wDTz