version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: nuget restore CSDiscord.sln
build:
  project: CSDiscord.sln
  publish_wap: true
  parallel: true
  verbosity: normal
before_test:
  - dotnet --version
test_script:
  - dotnet xunit
deploy:
- provider: WebDeploy
  server: https://csdiscordservice.scm.azurewebsites.net:443/msdeploy.axd?site=csdiscordservice
  website: csdiscordservice
  username: $csdiscordservice
  password:
    secure: 7ZZv5auxcejdquiVPI7WEu+gJ7DHESAN0yudFAYMpMd4enJChl20Fw5XVNyYW8HB+OGP4THbSqCN/qorYExNBw==
  artifact: CSDiscordService
  remove_files: true
  app_offline: true