version: 1.0.{build}
image: Visual Studio 2017 Preview
configuration: Release
platform: Any CPU
pull_requests:
  do_not_increment_build_number: true
install:
  - dotnet --info
  - ps: choco install docker-compose
before_build:
  - dotnet restore CSDiscordService\CSDiscordService.csproj --configfile ..\.nuget\nuget.config
  - dotnet restore CSDiscordService.Tests\CSDiscordService.Tests.csproj --configfile ..\.nuget\nuget.config
build:
  project: CSDiscord.sln
  verbosity: minimal
test_script:
  - docker run -d -e "tokens=test" -p 80:80/tcp --name CSDiscord --net nat csdiscordservice
  - ps: |
      $json = (& "docker" "inspect" "CSDiscord" | ConvertFrom-Json)
      $address= $json.NetworkSettings.Networks.nat.ipaddress
      iwr -uri "http://$address/Eval" -method POST -contentType "text/plain" -body "1+1" -UseBasicParsing -Headers @{"Authorization"="Token test"}
  - docker stop CSDiscord
  - docker rm CSDiscord
deploy_script:
  - ps: |
      $tag = $env:APPVEYOR_REPO_TAG_NAME
      if([System.String]::IsNullOrWhitespace($tag)) {
        $tag = "untagged"
      }
      docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"
      docker tag csdiscordservice cisien/csdiscord:$tag
      docker push cisien/csdiscord:$tag
artifacts:
- path: '**\*'
  name: everything
deploy:
- provider: Environment
  name: docker
environment:
  CLI_VERSION: 2.0.0-preview2-006497
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOCKER_USER:
    secure: ry9x9cQ9gzMNaPOd45RSHQ==
  DOCKER_PASS:
    secure: AXXeju7g+0ZE1ZMW2TKcXfW6+CMT70ZDh5iWYE5Bg80=
  TOKENS:
    secure: 20GDZBJStUXBheGueyX+iIXiRK6E/npU6vn2OA6s+NzIq96C+33xZblQbSwUt6BtYCr3duMGuiwaCayUR20SYVWCYo1I2IBZq+uUUtTZVfk=


