version: 1.0.{build}
image: Visual Studio 2017 Preview
configuration: Release
platform: Any CPU
pull_requests:
  do_not_increment_build_number: true
install:
  - dotnet --info
  - ps: choco install docker-compose
build:
  project: CSDiscord.sln
  verbosity: minimal
test_script:
  - cd .\CSDiscordService.Tests\
  - dotnet xunit -parallel collections
  - cd ..
deploy_script:
  - ps: .\deploy.ps1
environment:
  api_token:
    secure: GroejrzfkoqNfBomrM4kTrBhT9PoueDewcScZe81dYrqU42xc4WRH2gbNib7wDTz
  CLI_VERSION: 2.0.0-preview2-006497
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOCKER_USER:
    secure: ry9x9cQ9gzMNaPOd45RSHQ==
  DOCKER_PASS:
    secure: AXXeju7g+0ZE1ZMW2TKcXfW6+CMT70ZDh5iWYE5Bg80=
