version: 1.0.{build}
image: Visual Studio 2017 Preview
configuration: Release
platform: Any CPU
pull_requests:
  do_not_increment_build_number: true
install:
  - dotnet --info
  - ps: choco install docker-compose
before_build:
  - dotnet restore CSDiscordService\CSDiscordService.csproj --configfile ..\.nuget\nuget.config
  - dotnet restore CSDiscordService.Tests\CSDiscordService.Tests.csproj --configfile ..\.nuget\nuget.config
build:
  project: CSDiscord.sln
  verbosity: minimal
test_script:
  - cd .\CSDiscordService.Tests\
  - dotnet xunit
  - cd ..
  - docker run -d -e "tokens=test" -p 80:80/tcp --name CSDiscord --ip 172.17.240.10 --net nat csdiscordservice
  - ps: sleep -Seconds 60
  - ps: iwr -uri http://172.16.20.10/Eval -method POST -contentType 'text/plain' -body '1+1' -UseBasicParsing -Headers @{"Authorization"="Token test"}
  - docker stop CSDiscord
  - docker rm CSDiscord
deploy_script:
  - ps: .\deploy.ps1
environment:
  api_token:
    secure: GroejrzfkoqNfBomrM4kTrBhT9PoueDewcScZe81dYrqU42xc4WRH2gbNib7wDTz
  CLI_VERSION: 2.0.0-preview2-006497
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOCKER_USER:
    secure: ry9x9cQ9gzMNaPOd45RSHQ==
  DOCKER_PASS:
    secure: AXXeju7g+0ZE1ZMW2TKcXfW6+CMT70ZDh5iWYE5Bg80=
