version: '3'

services:
  csdiscordservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80"
    build:
      context: ./CSDiscordService
      dockerfile: Dockerfile-dev
networks:
  default:
    external:
      name: nat
